Python: Add 'low' Severity Level to ContentFilterResultSeverity Enum (#9103)
### Motivation and Context

I am submitting this pull request to address a missing definition in the
`ContentFilterResultSeverity` enumeration within the Azure OpenAI
content filtering framework. This omission has been causing an exception
when the content filter should detect certain conditions.

### Description

Currently, when a content filter exception is triggered, it results in a
`ValueError` due to the absence of a 'low' severity level in the
`ContentFilterResultSeverity` enum. The error traceback is as follows:

```bash
Traceback (most recent call last):                                                                                                                                                                                                                                                                                                                                                             
  File ".venv/lib/python3.11/site-packages/semantic_kernel/connectors/ai/chat_completion_client_base.py", line 139, in get_chat_message_contents                                                                                                                                                                                                  
    completions = await self._inner_get_chat_message_contents(chat_history, settings)                                                                                                                                                                                                                                                                                                          
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                          
  File ".venv/lib/python3.11/site-packages/semantic_kernel/utils/telemetry/model_diagnostics/decorators.py", line 83, in wrapper_decorator                                                                                                                                                                                                        
    return await completion_func(*args, **kwargs)                                                                                                                                                                                                                                                                                                                                              
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                                                              
  File ".venv/lib/python3.11/site-packages/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py", line 88, in _inner_get_chat_message_contents                                                                                                                                                                          
    response = await self._send_request(request_settings=settings)                                                                                                                                                                                                                                                                                                                             
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                                             
  File ".venv/lib/python3.11/site-packages/semantic_kernel/connectors/ai/open_ai/services/open_ai_handler.py", line 54, in _send_request                                                                                                                                                                                                          
    raise ContentFilterAIException(                                                                                                                                                                                                                                                                                                                                                            
          ^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                                                                            
  File ".venv/lib/python3.11/site-packages/semantic_kernel/connectors/ai/open_ai/exceptions/content_filter_ai_exception.py", line 87, in __init__                                                                                                                                                                                                 
    self.content_filter_result = {                                                                                                                                                                                                                                                                                                                                                             
                                ^                                                                                                                                                                                                                                                                                                                                                             
  File ".venv/lib/python3.11/site-packages/semantic_kernel/connectors/ai/open_ai/exceptions/content_filter_ai_exception.py", line 88, in <dictcomp>                                                                                                                                                                                               
    key: ContentFilterResult.from_inner_error_result(values)                                                                                                                                                                                                                                                                                                                                   
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                                                   
  File ".venv/lib/python3.11/site-packages/semantic_kernel/connectors/ai/open_ai/exceptions/content_filter_ai_exception.py", line 43, in from_inner_error_result                                                                                                                                                                                  
    severity=ContentFilterResultSeverity(                                                                                                                                                                                                                                                                                                                                                      
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
ValueError: 'low' is not a valid ContentFilterResultSeverity 
```

In some cases, Azure OpenAI's Content Filter assigns a 'low' severity
level. For instance, the error message below indicates such a scenario:

```bash
openai.BadRequestError: Error code: 400 - {'error': {'message': "The response was filtered due to the prompt triggering Azure OpenAI's content management policy. Please modify your prompt and retry. To learn more about our content filtering policies please read our documentation: https://go.microsoft.com/fwlink/?linkid=2198766", ... 'severity': 'low'}}}}
```

To resolve this issue, I have added 'LOW' as a valid severity level in
the ContentFilterResultSeverity enum as shown below:

```py
class ContentFilterResultSeverity(Enum):
    """The severity of the content filter result."""
    HIGH = "high"
    MEDIUM = "medium"
    SAFE = "safe"
    LOW = "low"  # Added this line
```

### Contribution Checklist

<!-- Before submitting this PR, please make sure: -->

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution
Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md)
and the [pre-submission formatting
script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts)
raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

Co-authored-by: Evan Mattson <35585003+moonbox3@users.noreply.github.com>